name: CI
on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:
  workflow_dispatch:

jobs:

  test:
    name: Test
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3.0.2
      with:
        dotnet-version: |
          5.0.x
          3.1.x

    - name: Test
      shell: pwsh
      run: dotnet test --logger:"console;verbosity=detailed" -c Release

  build:
    name: Push nuget packages if a new tag is pushed
    needs: test
    if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    env:
      ProjectName: URIScheme

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3.0.2
      with:
        dotnet-version: 5.0.x

    - name: Build
      shell: pwsh
      run: dotnet build -c Release

    - name: Push nuget packages
      shell: pwsh
      run: |
        dotnet nuget push ${{ env.ProjectName }}\bin\Release\*.nupkg -s https://nuget.pkg.github.com/HMBSbige -k ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
        dotnet nuget push ${{ env.ProjectName }}\bin\Release\*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NuGetAPIKey }} --skip-duplicate
